
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('questions').del()
    .then(function () {
      // Inserts seed entries
      return knex('questions').insert([
        { question: 'Quem era o homem mais sedutor do mundo?', answer_1: 'DOM JUAN', answer_2: 'DOM ANTÔNIO', answer_3: 'DOM MARCO', answer_4: 'DOM CARLOS', answer_correct: 1 },
        { question: 'De quantos anos é constituído um século?', answer_1: '50', answer_2: '100', answer_3: '1.000', answer_4: '1.500', answer_correct: 2 },
        { question: 'Qual é o coletivo de cães?', answer_1: 'MATILHA', answer_2: 'REBANHO', answer_3: 'CARDUME', answer_4: 'MANADA', answer_correct: 1 },
        { question: 'Segundo a Bíblia, em que rio Jesus foi batizado por João Batista?', answer_1: 'NO RIO NILO', answer_2: 'NO RIO SENA', answer_3: 'NO RIO RENO', answer_4: 'NO RIO JORDÃO', answer_correct: 4 },
        { question: 'Qual é a maior floresta do planeta?', answer_1: 'NEGRA', answer_2: 'DE SHERWOOD', answer_3: 'DA TIJUCA', answer_4: 'AMAZÔNICA', answer_correct: 4 },
        { question: 'Qual é o naipe do baralho que tem o desenho de coração?', answer_1: 'OUROS', answer_2: 'PAUS', answer_3: 'COPAS', answer_4: 'ESPADAS', answer_correct: 3 },
        { question: 'Qual atriz estrelou no filme: “A lagoa azul”?', answer_1: 'ALICIA SILVERSTONE', answer_2: 'BROOKE SHIELDS', answer_3: 'JULIA ROBERTS', answer_4: 'JESSICA LANGE', answer_correct: 2 },
        { question: 'Qual casal foi expulso do Paraíso?', answer_1: 'SANSÃO E DALILA', answer_2: 'JOSÉ E MARIA', answer_3: 'SARA E ABRAÃO', answer_4: 'ADÃO  E EVA', answer_correct: 4 },
        { question: 'Segundo os contos, qual animal ao ser beijado se transforma em príncipe?', answer_1: 'CAVALO', answer_2: 'CÃO', answer_3: 'GATO', answer_4: 'SAPO', answer_correct: 4 },
        { question: 'Qual é o santo que só acreditou vendo?', answer_1: 'SANTO ANTÔNIO', answer_2: 'SÃO JUDAS TADEU', answer_3: 'SÃO PEDRO', answer_4: 'SÃO TOMÉ', answer_correct: 4 },
        { question: 'Qual é o fruto conhecido no nordeste do Brasil como “jerimum”?', answer_1: 'CAJU', answer_2: 'ABÓBORA', answer_3: 'CHUCHU', answer_4: 'COCO', answer_correct: 2 },
        { question: 'Em qual parte do corpo humano são implantadas as “pontes de safena”?', answer_1: 'ESTÔMAGO', answer_2: 'INTESTINO', answer_3: 'PULMÃO', answer_4: 'CORAÇÃO', answer_correct: 4 },
        { question: 'Como é conhecido o jogador Edmundo?', answer_1: 'TIGRÃO', answer_2: 'GATINHO', answer_3: 'ANIMAL', answer_4: 'COBRA', answer_correct: 3 },
        { question: 'Na literatura, quem foi o criador da boneca Emília?', answer_1: 'MONTEIRO LOBATO', answer_2: 'MAURÍCIO DE SOUZA', answer_3: 'WALT DISNEY', answer_4: 'JORGE AMADO', answer_correct: 1 },
        { question: 'Quem é o primeiro substituto do Presidente?', answer_1: 'VEREADOR', answer_2: 'VICE-PRESIDENTE', answer_3: 'SENADOR', answer_4: 'DEPUTADO', answer_correct: 2 },
        { question: 'Segundo o romance, que animal era “Moby Dick”?', answer_1: 'TUBARÃO', answer_2: 'GOLFINHO', answer_3: 'POLVO', answer_4: 'BALEIA', answer_correct: 4 },
        { question: 'Qual é o animal que representa o signo de áries?', answer_1: 'TOURO', answer_2: 'LEÃO', answer_3: 'CARNEIRO', answer_4: 'BODE', answer_correct: 3 },
        { question: 'Que animal é o Pateta?', answer_1: 'CAVALO', answer_2: 'BURRO', answer_3: 'CACHORRO', answer_4: 'RAPOSA', answer_correct: 3 },
        { question: 'Em qual cidade está o Cristo Redentor do Corcovado?', answer_1: 'RIO DE JANEIRO', answer_2: 'SÃO PAULO', answer_3: 'CURITIBA', answer_4: 'BELO HORIZONTE', answer_correct: 1 },
        { question: 'Quem é conhecido como o “playboy brasileiro”?', answer_1: 'JOÃOZINHO TRINTA', answer_2: 'ZECA PAGODINHO', answer_3: 'CHIQUINHO SCARPA', answer_4: 'CHICO BUARQUE', answer_correct: 3 },
        { question: 'Quantos centímetros equivalem a um metro?', answer_1: '10', answer_2: '100', answer_3: '1000', answer_4: '10000', answer_correct: 2 },
        { question: 'Qual é o nome do macho da abelha?', answer_1: 'ZÂNGÃO', answer_2: 'ABELHÃO', answer_3: 'RUFIÃO', answer_4: 'PULGÃO', answer_correct: 1 },
        { question: 'Qual é o inseto que transmite a doença de Chagas?', answer_1: 'ABELHA', answer_2: 'BARATA', answer_3: 'BARBEIRO', answer_4: 'PULGA', answer_correct: 3 },
        { question: 'Qual é o nome do conjunto de dados estatísticos sobre uma população?', answer_1: 'CENSO', answer_2: 'CONTAGEM', answer_3: 'MARCAÇÃO', answer_4: 'REGISTRO', answer_correct: 1 },
        { question: 'Qual ator imortalizou o personagem “Zé Bonitinho”?', answer_1: 'RONI CÓCEGAS', answer_2: 'JORGE LOREDO', answer_3: 'DAVI PINHEIRO', answer_4: 'ARNAUD RODRIGUES', answer_correct: 2 },
        { question: 'Qual a cantora conhecida como “A rainha dos caminhoneiros”?', answer_1: 'ROBERTA MIRANDA', answer_2: 'MARIA BETHÂNIA', answer_3: 'SULA MIRANDA', answer_4: 'RITA CADILLAC', answer_correct: 3 },
        { question: 'Qual é o nome da missa rezada no Natal?', answer_1: 'CAMPAL', answer_2: 'DO GALO', answer_3: 'DO VATICANO', answer_4: 'DE SÉTIMO DIA', answer_correct: 2 },
        { question: 'Qual é a orixá conhecida como “A rainha do mar”?', answer_1: 'MAMÃE OXUM', answer_2: 'IEMANJÁ', answer_3: 'AXÉ', answer_4: 'IANSÃ', answer_correct: 2 },
        { question: 'No julgamento de Jesus, quem disse a frase: “Eu lavo minhas mãos”?', answer_1: 'BARRABÁS', answer_2: 'TIBÉRIO', answer_3: 'PÔNCIO PILATOS', answer_4: 'JUDAS', answer_correct: 3 },
        { question: 'O que está no centro da Terra?', answer_1: 'MANTO', answer_2: 'NÚCLEO', answer_3: 'HIDROSFERA', answer_4: 'LITOSFERA', answer_correct: 2 },
        { question: 'Qual é o esporte praticado por Fernando Scherer, o Xuxa?', answer_1: 'CICLISMO', answer_2: 'VÔLEI DE PRAIA', answer_3: 'NATAÇÃO', answer_4: 'SURF', answer_correct: 3 },
        { question: 'Quem libertou os escravos em 1888?', answer_1: 'JOANA D’ARC', answer_2: 'ANITA GARIBALDI', answer_3: 'PRINCESA ISABEL', answer_4: 'IMPERATRIZ LEOPOLDINA', answer_correct: 3 },
        { question: 'Quem fez sucesso com a personagem “Tiazinha”?', answer_1: 'SUZANA WERNER', answer_2: 'JOANA PRADO', answer_3: 'LETÍCIA SPILLER', answer_4: 'SUZANA ALVES', answer_correct: 4 },
        { question: 'Quantos eram os anões da história “A branca de neve”?', answer_1: 'SEIS', answer_2: 'SETE', answer_3: 'OITO', answer_4: 'NOVE', answer_correct: 2 },
        { question: 'Como eram chamados os navios que traziam os escravos para o Brasil?', answer_1: 'BRANQUEIROS', answer_2: 'PESQUEIROS', answer_3: 'NEGREIROS', answer_4: 'COSTEIROS', answer_correct: 3 },
        { question: 'De qual grupo de samba fez parte o humorista “Mussum”?', answer_1: 'FUNDO DE QUINTAL', answer_2: 'TITULARES DO RITMO', answer_3: 'ORIGINAIS DO SAMBA', answer_4: 'BANDA BRASIL', answer_correct: 3 },
        { question: 'Como se chama o lugar onde ficam as mulheres do sultão?', answer_1: 'HARÉM', answer_2: 'LABIRINTO', answer_3: 'COLISEU', answer_4: 'CHOUPANA', answer_correct: 1 },
        { question: 'Quantas cores compõem o arco-íris?', answer_1: '3', answer_2: '7', answer_3: '12', answer_4: '22', answer_correct: 2 },
        { question: 'Qual é o nome da mulher de Fred Flintstone?', answer_1: 'BETH', answer_2: 'WILMA', answer_3: 'MARGARIDA', answer_4: 'CLARABELA', answer_correct: 2 },
        { question: 'Por quem foi dita a frase: “Abra-te Sézamo”?', answer_1: 'D. PEDRO I', answer_2: 'HÉRCULES', answer_3: 'ALI BABÁ', answer_4: 'DUNGA', answer_correct: 3 },
        { question: 'Em qual cidade está localizada a famosa estátua da Liberdade?', answer_1: 'LONDRES', answer_2: 'NOVA YORK', answer_3: 'PARIS', answer_4: 'MADRI', answer_correct: 2 },
        { question: 'Qual destes personagens não veste uma capa?', answer_1: 'SUPER-HOMEM', answer_2: 'BATMAN', answer_3: 'WOLVERINE', answer_4: 'ZORRO', answer_correct: 3 },
        { question: 'Quem é considerado o rei do mundo animal?', answer_1: 'ELEFANTE', answer_2: 'GORILA', answer_3: 'LEÃO', answer_4: 'RINOCERONTE', answer_correct: 3 },
        { question: 'Qual é o livro mais impresso no mundo?', answer_1: 'JUBIABÁ', answer_2: 'BÍBLIA', answer_3: 'GABRIELA, CRAVO E CANELA', answer_4: 'TERRAS DO SEM FIM', answer_correct: 2 },
        { question: 'Qual é o nome do osso da coxa do ser humano?', answer_1: 'FÊMUR', answer_2: 'TÍBIA', answer_3: 'PERÔNIO', answer_4: 'ÚMERO', answer_correct: 1 },
        { question: 'Como se chama o espaço de tempo entre o nascer e o pôr do-sol?', answer_1: 'MADRUGADA', answer_2: 'DIA', answer_3: 'NOITE', answer_4: 'SEMANA', answer_correct: 2 },
        { question: 'Os nomes Batman e Rainman referem-se a quê?', answer_1: 'ARTISTAS DE TEATRO', answer_2: 'FILMES DE CINEMA', answer_3: 'CONJUNTOS DE ROCK', answer_4: 'MARCAS DE CIGARRO', answer_correct: 2 },
        { question: 'De acordo com o ditado, o que “não adianta chorar”?', answer_1: 'FOLHAS CAÍDAS', answer_2: 'LEITE DERRAMADO', answer_3: 'DOCE QUEIMADO', answer_4: 'PÃO VELHO', answer_correct: 2 },
        { question: 'Em qual destas atividades a corda tem um papel vital?', answer_1: 'SURFE', answer_2: 'CICLISMO', answer_3: 'TOURADA', answer_4: 'PÁRA-QUEDISMO', answer_correct: 4 },
        { question: 'Como se chama o boneco controlado por cordas?', answer_1: 'ROBÔ', answer_2: 'MARIONETE', answer_3: 'ANDRÓIDE', answer_4: 'MANEQUIM', answer_correct: 2 },
        { question: 'Como são chamados os pedaços de gelo que caem durante a chuva?', answer_1: 'GRANITO', answer_2: 'GRANIZO', answer_3: 'PICOLÉ', answer_4: 'NEVE', answer_correct: 2 },
        { question: 'Qual Deus é descrito como uma criança gorducha com arco e flecha?', answer_1: 'CUPIDO', answer_2: 'ZEUS', answer_3: 'MERCÚRIO', answer_4: 'NETUNO', answer_correct: 1 },
        { question: 'No desenho “Papa-léguas” qual é o som feito pela ave corredora?', answer_1: 'PING! PING!', answer_2: 'UGA! UGA!', answer_3: 'BIP! BIP!', answer_4: 'VRUM! VRUM!', answer_correct: 3 },
        { question: 'Qual destes alimentos devemos consumir em menor quantidade?', answer_1: 'VEGETAIS', answer_2: 'GORDURAS', answer_3: 'LEGUMES', answer_4: 'FRUTAS', answer_correct: 2 },
        { question: 'O que Cinderela perdeu ao sair do baile do palácio real?', answer_1: 'BOLSA', answer_2: 'LUVA', answer_3: 'CARTEIRA DE MOTORISTA', answer_4: 'SAPATO DE CRISTAL', answer_correct: 4 },
        { question: 'Como se chama a luz que guia os navios em áreas de risco?', answer_1: 'VELA', answer_2: 'FAROL', answer_3: 'FOGUEIRA', answer_4: 'LAMPARINA', answer_correct: 2 },
        { question: 'Em qual jogo o ganhador grita o nome do jogo em sinal de vitória?', answer_1: 'ESCONDE-ESCONDE', answer_2: 'BINGO', answer_3: 'BANCO IMOBILIÁRIO', answer_4: 'XADREZ', answer_correct: 2 },
        { question: 'Um analgésico é um agente para:?', answer_1: 'TRATAMENTO DO INTESTINO', answer_2: 'ALÍVIO DE ESTRESSE', answer_3: 'ALÍVIO DA DOR', answer_4: 'TRATAMENTO DA CASPA', answer_correct: 3 },
        { question: 'Qual é a cidade do Batman?', answer_1: 'GOTHAM CITY', answer_2: 'METRÓPOLIS', answer_3: 'PLEASANTVILLE', answer_4: 'ANYTOWN', answer_correct: 1 },
        { question: 'De que é feito o pé-de-moleque?', answer_1: 'AMENDOIM', answer_2: 'CASTANHA', answer_3: 'ALCAPARRA', answer_4: 'ABACATE', answer_correct: 1 },
        { question: 'O que Rapunzel jogava pela janela?', answer_1: 'PERNA', answer_2: 'BRAÇO', answer_3: 'FAMÍLIA', answer_4: 'TRANÇA', answer_correct: 4 },
        { question: 'O que se joga na neve para ajudar a derretê-la?', answer_1: 'AÇÚCAR', answer_2: 'ORÉGANO', answer_3: 'SAL', answer_4: 'PIMENTA', answer_correct: 3 },
        { question: 'Qual desses heróis de ficção usa uma máscara?', answer_1: 'ROBIN HOOD', answer_2: 'SIMBAD', answer_3: 'INDIANA JONES', answer_4: 'ZORRO', answer_correct: 4 },
        { question: 'Quantos anos tem um milênio?', answer_1: '100', answer_2: '500', answer_3: '1.000', answer_4: '10.000', answer_correct: 3 },
        { question: 'Quanto tempo a Terra leva para completar uma órbita ao redor do sol?', answer_1: 'UM ANO', answer_2: 'UM MÊS', answer_3: 'UMA SEMANA', answer_4: 'UM SÉCULO', answer_correct: 1 },
        { question: 'Onde a mamãe canguru carrega o filhote?', answer_1: 'NA ORELHA', answer_2: 'NAS COSTAS', answer_3: 'NA BOCA', answer_4: 'NA BOLSA', answer_correct: 4 },
        { question: 'Como é o nome da cabeleira que envolve a cabeça do leão?', answer_1: 'TOPETE', answer_2: 'CACHO', answer_3: 'JUBA', answer_4: 'PERUCA', answer_correct: 3 },
        { question: '“Um por todos e todos por um” é o grito de qual destes grupos?', answer_1: 'EXTRATERRESTRES', answer_2: 'FAMÍLIA ROBINSON', answer_3: 'POWER RANGERS', answer_4: 'TRÊS MOSQUETEIROS', answer_correct: 4 },
        { question: 'O que é a morsa?', answer_1: 'UM RÉPTIL', answer_2: 'UM MAMÍFERO', answer_3: 'UM PEIXE', answer_4: 'UM CRUSTÁCEO', answer_correct: 2 },
        { question: 'Qual personagem de desenho animado é rico e pão-duro?', answer_1: 'TIO PATINHAS', answer_2: 'PATETA', answer_3: 'MICKEY', answer_4: 'PATO DONALD', answer_correct: 1 },
        { question: 'O que é um croissant?', answer_1: 'LICOR', answer_2: 'DOCE', answer_3: 'TEMPERO', answer_4: 'PÃO', answer_correct: 4 },
        { question: 'Qual exame é usado para comprovar a paternidade?', answer_1: 'DE SANGUE', answer_2: 'DE DNA', answer_3: 'DE URINA', answer_4: 'DE CONSCIÊNCIA', answer_correct: 2 },
        { question: 'Tarsila do Amaral era uma:?', answer_1: 'DANÇARINA', answer_2: 'ATRIZ', answer_3: 'MÉDICA', answer_4: 'PINTORA', answer_correct: 4 },
        { question: 'Os bairros mais afastados do centro da cidade chamam-se:?', answer_1: 'RESIDENCIAIS', answer_2: 'COMERCIAIS', answer_3: 'SUBURBANOS', answer_4: 'INDUSTRIAIS', answer_correct: 3 },
        { question: 'Qual destas palavras é sinônimo de equívoco?', answer_1: 'ACERTO', answer_2: 'EQUITAÇÃO', answer_3: 'ENGANO', answer_4: 'CAVALO', answer_correct: 3 },
        { question: 'Qual destes itens não é encontrado em uma bicicleta comum?', answer_1: 'AIR BAG', answer_2: 'GUIDÃO', answer_3: 'SELIM', answer_4: 'CORRENTE', answer_correct: 1 },
        { question: 'Que nome se dá a cada parte do esqueleto?', answer_1: 'CAVEIRA', answer_2: 'OSSO', answer_3: 'ARCADA', answer_4: 'BACIA', answer_correct: 2 },
        { question: 'Nas religiões afro-brasileiras, quem é o Deus da Guerra?', answer_1: 'TUPÃ', answer_2: 'OGUM', answer_3: 'SENHOR DO BONFIM', answer_4: 'ZEUS', answer_correct: 2 },
        { question: 'Com o que era acionado o motor dos antigos automóveis?', answer_1: 'CHAVE DE FENDA', answer_2: 'BARBANTE', answer_3: 'PARAFUSO', answer_4: 'MANIVELA', answer_correct: 4 },
        { question: 'Qual presidente brasileiro renunciou em 1992?', answer_1: 'ITAMAR FRANCO', answer_2: 'FERNANDO COLLOR', answer_3: 'JOSÉ SARNEY', answer_4: 'FIGUEIREDO', answer_correct: 2 },
        { question: 'O que é uma sucuri?', answer_1: 'COBRA', answer_2: 'REFRIGERANTE', answer_3: 'TIPO DE LARANJA', answer_4: 'VASO INDÍGENA', answer_correct: 1 },
        { question: 'Qual destes é um personagem de Monteiro Lobato?', answer_1: 'MÔNICA', answer_2: 'MAGALI', answer_3: 'NARIZINHO', answer_4: 'MULHER MARAVILHA', answer_correct: 3 },
        { question: 'Qual é o material usado para fazer a borracha?', answer_1: 'DUREX', answer_2: 'LÁTEX', answer_3: 'PIREX', answer_4: 'XÉROX', answer_correct: 2 },
        { question: 'Quantos atletas participam, por equipe, da prova 4 por 100?', answer_1: 'CEM', answer_2: 'DEZ', answer_3: 'OITO', answer_4: 'QUATRO', answer_correct: 4 },
        { question: 'Para que serve um dedal?', answer_1: 'ARRUMAR AGULHAS', answer_2: 'CORTAR LINHAS', answer_3: 'PROTEGER O DEDO', answer_4: 'CURAR FERIDAS', answer_correct: 3 },
        { question: 'O que se encontra no final do arco-íris?', answer_1: 'SACO DE DIAMANTES', answer_2: 'POTE DE OURO', answer_3: 'BARRA DE PRATA', answer_4: 'ESMERALDAS', answer_correct: 2 },
        { question: 'Em qual destes lugares pode-se encontrar um oásis?', answer_1: 'NO ROCHEDO', answer_2: 'NA FLORESTA TROPICAL', answer_3: 'NO DESERTO', answer_4: 'NA SAVANA', answer_correct: 3 },
        { question: 'Qual destas frutas é associada ao Natal?', answer_1: 'NOZ', answer_2: 'BANANA', answer_3: 'TANGERINA', answer_4: 'JABUTICABA', answer_correct: 1 },
        { question: 'De que cor fica a lagosta quando adequadamente cozida?', answer_1: 'PRETA', answer_2: 'VERMELHA', answer_3: 'VERDE', answer_4: 'AMARELA', answer_correct: 2 },
        { question: 'Qual destas músicas foi composta por Adoniran Barbosa?', answer_1: 'TREM DAS ONZE', answer_2: 'MÁSCARA NEGRA', answer_3: 'CHIQUITA BACANA', answer_4: 'JARDINEIRA', answer_correct: 1 },
        { question: 'O que é labrador?', answer_1: 'RAÇA DE GATO', answer_2: 'RAÇA DE GADO', answer_3: 'RAÇA DE CACHORRO', answer_4: 'RAÇA DE CAVALO', answer_correct: 3 },
        { question: 'Um cleptomaníaco tem como principal característica:?', answer_1: 'MEDO DE ESCURO', answer_2: 'MANIA DE ROUBAR', answer_3: 'MEDO DE ALTURA', answer_4: 'MANIA DE PERSEGUIÇÃO', answer_correct: 2 },
        { question: 'Como se chama a avenida do sambódromo do Rio de Janeiro?', answer_1: 'MARQUÊS DE JACAREÍ', answer_2: 'MARQUÊS DE SAPUCAÍ', answer_3: 'MARQUÊS DE SAMBEI E CAÍ', answer_4: 'MARQUÊS DE SÃO VICENTE', answer_correct: 2 },
        { question: 'Qual nome é dado à barriga da perna?', answer_1: 'AGULHA', answer_2: 'BÍCEPS', answer_3: 'MÚSCULO', answer_4: 'PANTURRILHA', answer_correct: 4 },
        { question: 'Quem não tem domicílio fixo?', answer_1: 'O NÔMADE', answer_2: 'O VIAJOR', answer_3: 'O VIAJANTE', answer_4: 'O PASSEADOR', answer_correct: 1 },
        { question: 'Quantos espaços tem no Jogo da Velha?', answer_1: 'SEIS', answer_2: 'SETE', answer_3: 'OITO', answer_4: 'NOVE', answer_correct: 4 },
        { question: 'Como se chama a armação dos óculos?', answer_1: 'RODA', answer_2: 'EIXO', answer_3: 'ARCO', answer_4: 'ARO', answer_correct: 4 },
        { question: 'A pessoa que planeja e cria jardins e parques chama-se: ?', answer_1: 'FLORISTA', answer_2: 'PAISAGISTA', answer_3: 'FLORICULTOR', answer_4: 'ARTISTA', answer_correct: 2 },
        { question: 'Qual nome é dado à criança ainda não batizada?', answer_1: 'PAGÃO', answer_2: 'ANÃO', answer_3: 'CHORÃO', answer_4: 'CRISTÃO', answer_correct: 1 },
        { question: 'Qual destes órgãos não faz parte do sistema digestivo?', answer_1: 'BRÔNQUIOS', answer_2: 'BOCA', answer_3: 'FARINGE', answer_4: 'INTESTINO', answer_correct: 1 },

      ]);
    });
};
